project1/project1/urls.py
from django.contrib import admin
from django.urls import path
from budget import views as budget_view
from core import views as core_view
from tasks import views as tasks_view
from log import views as log_view
from journal import views as journal_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', core_view.core, name='core'),
    path('tasks/', tasks_view.tasks, name='tasks'),
    path('budget/', budget_view.budget, name='budget'),
    path('join/', log_view.join, name='join'),
    path('login/', log_view.user_login, name='login'),
    path('logout/', log_view.user_logout, name='logout'),
    path('add_tasks/', tasks_view.add_tasks, name='add_tasks'),
    path('edit_tasks/<str:pk>/', tasks_view.edit_tasks, name='edit_tasks'),
    path('tasks/delete/<str:pk>/', tasks_view.delete, name='tasks/delete'),
    path('budget/delete/<str:pk>/', budget_view.delete, name='budget/delete'),
    path('journal/delete/<str:pk>/', journal_view.delete, name='journal/delete'),
    path('add_budget/', budget_view.add_budget, name='add_budget'),
    path('edit_budget/<str:pk>/', budget_view.edit_budget, name='edit_budget'),
    path('toggle/<str:pk>/', tasks_view.toggle, name='toggle'),
    path('journal/', journal_view.journal, name='journal'),
    path('add_journal/', journal_view.add_journal, name='add_journal'),
    path('edit_journal/<str:pk>/', journal_view.edit_journal, name='edit_journal'),
]

project1/tasks/models.py
from django.db import models
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import gettext as _

# Create your models here.



class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    # tasks_view_hide_completed = models.BooleanField(blank = False, label = 'tasks_view_hide_completed', widget=forms.CheckboxInput(attrs={'onclick': 'this.form.submit()'}))
      # external = forms.BooleanField(label=_('External link'), required=False)
    description = models.CharField(max_length=20)
    CATAGORY_CHOICES = (
    ('A', 'Home'),
    ('B', 'School'),
    ('C', 'Work'),
    ('D', 'Self-Improvment'),
    ('E', 'Other'),
    )

    TRUE_FALSE_CHOICES = (
    ('True', 'Yes'),
    ('False', 'No')
    )

    catagory = models.CharField(max_length=8, choices=CATAGORY_CHOICES)
    completed = models.CharField(max_length=8, choices = TRUE_FALSE_CHOICES, default='No')

project1/tasks/forms.py
from django import forms
from tasks.models import Task
from django.forms import ModelForm
from core.models import UserProfile



class ADD_TASKFORM(ModelForm):
    class Meta:
        model = Task
        fields = ('description', 'catagory')

class EDIT_TASKFORM(ModelForm):
    class Meta:
        model = Task
        fields = ('description', 'catagory')

class SHOW_HIDE(ModelForm):
    class Meta:
        model = UserProfile
        fields = ('tasks_view_hide_completed',)

project1/tasks/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from tasks.models import Task
from tasks.forms import ADD_TASKFORM, EDIT_TASKFORM, SHOW_HIDE
from django.contrib.auth.decorators import login_required
from django.apps import apps
from django.contrib.auth.models import User
UserProfile = apps.get_model('core', 'UserProfile')
import pdb

# Create your views here.
@login_required(login_url='/login/')
def tasks(request):
    show_hide = SHOW_HIDE()
    if (not Task.objects.filter(user=request.user)):
        return render(request, 'tasks/tasks.html')
        if (request.method == "POST"):
            user_profile = UserProfile.objects.filter(user=request.user).get()
            if(user_profile.tasks_view_hide_completed == 'False'):
                task_objects = Task.objects.filter(user=request.user)
                con = {'task_objects': task_objects, "SHOW_HIDE" : show_hide}
                return render(request, 'tasks/tasks.html', con)
                user_profile.tasks_view_hide_completed = 'True'
            else:
                task_objects = Task.objects.filter(user=request.user, completed='No')
                con = {'task_objects': task_objects, "SHOW_HIDE" : show_hide}
                return render(request, 'tasks/tasks.html', con)
                user_profile.tasks_view_hide_completed = 'False'

    else:
        task_objects = Task.objects.filter(user=request.user)
        con = {'task_objects': task_objects, "SHOW_HIDE" : show_hide}
        return render(request, 'tasks/tasks.html', con)

@login_required(login_url='/login/')
def add_tasks(request):
    if (request.method == "POST"):
        add_taskform = ADD_TASKFORM(request.POST)
        if (add_taskform.is_valid()):
            task = add_taskform.save(commit=False)
            task.user = request.user
            task.save()
            return redirect("/tasks")
        else:
            # Form invalid, print errors to console
            page_data = { "ADD_TASKFORM": add_taskform }
            return render(request, 'tasks/add_tasks.html', page_data)

    else:
        add_taskform = ADD_TASKFORM()
        page_data = { "ADD_TASKFORM": add_taskform }
        return render(request, 'tasks/add_tasks.html', page_data)

@login_required(login_url='/login/')
def edit_tasks(request, pk):
    hh = Task.objects.get(id=pk)
    edit_taskform = EDIT_TASKFORM(instance = hh)

    if (request.method == "POST"):
        edit_taskform = EDIT_TASKFORM(request.POST, instance = hh)

        if (edit_taskform.is_valid()):
            task = edit_taskform.save(commit=False)
            task.user = request.user
            task.id = pk
            task.save()
            return redirect("/tasks")

        else:
            # Form invalid, print errors to console
            page_data = { "EDIT_TASKFORM": edit_taskform }
            return render(request, 'tasks/edit_tasks.html', page_data)

    else:

        page_data = { "EDIT_TASKFORM": edit_taskform }
        return render(request, 'tasks/edit_tasks.html', page_data)

@login_required(login_url='/login/')
def delete(request, pk):
    dele = Task.objects.get(id=pk)
    dele.delete()
    return redirect("/tasks")


@login_required(login_url='/login/')
def toggle(request, pk):
    tt = Task.objects.get(id=pk)

    if(tt.completed == 'Yes'):
        tt.completed = 'No'
    else:
        tt.completed = 'Yes'
    tt.save()
    return redirect("/tasks")

project1/templates/tasks/add_tasks.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title></title>
  {% include "shared_links.html" %}
</head>

<body>
  <div class="container">
    <div class = "jumbotron">
      <h1>Add Tasks</h1>
      <form method="POST">{% csrf_token %}
        <table>
            {{ ADD_TASKFORM.as_table }}
            <tr><td>
              <input type="submit" class="btn btn-primary" value = "Add Task"/>
            </td></tr>
        </table>
      </form>
    </div>
  </div>
</body>

project1/templates/tasks/edit_tasks.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title></title>
  {% include "shared_links.html" %}
</head>

<body>
  <div class="container">
    <div class = "jumbotron">
      <h1>Edit Tasks</h1>
      <form method="POST">{% csrf_token %}
        <table>
            {{ EDIT_TASKFORM.as_table }}
            <tr><td>
              <input type="submit" class="btn btn-primary" value = "Edit Task"/>
              <button onclick="window.location.href='/tasks'" type="button" class="btn btn-outline-success my-2 my-sm-0">Cancel</button>
            </tr>
        </table>
      </form>
    </div>
  </div>
</body>

project1/templates/tasks/tasks.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title></title>
  {% include "shared_links.html" %}
  {% include "delete.html" %}
  {% load static %}
  <script src="{% static 'JS/tasks.js' %}"></script>
  <link href="{%static 'CSS/core.css'%}" rel="stylesheet">
</head>

<body>
  <h2> Tasks </h2>

</table>
  <div class = "jumbotron">
  <table class="table table-bordered">
    <thead>
      <form action="/tasks/" method="POST">{% csrf_token %}
    {{ SHOW_HIDE.as_p }}
  </form>
    </div>
      <tr>
        <th scope="col">Description</th>
        <th scope="col">Catagory</th>
        <th scope="col">Completed</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>

        {% for row in task_objects %}
          <tr>
                <td> {{row.description}} </td>
                <td> {{row.get_catagory_display}} </td>
                <td> <a href="{% url 'toggle' row.id %}">{{row.get_completed_display}}</a> </td>
                <td><a class="btn btn-outline-success my-2 my-sm-0" href="{% url 'edit_tasks' row.id %}">Edit</button></a>
                  <a class="btn btn-danger" href="#" onclick="confirmDeleteModal({{row.id}})">Delete</a>


        </tr>
        {% endfor %}
    </tbody>
  </table>
  <button onclick="window.location.href='/add_tasks'" type="button" class="btn btn-info">Add Task</button>
</div>
<p> {{tt.catagory}} </p>
</body>